module.exports.DEFINED_ERRS = {
    AUTH_ERR: 'AUTH_ERR',
    FLASHCARD_VALIDATION_ERR: 'FLASHCARD_VALIDATION_ERR', 
    CATEGORY_VALIDATION_ERR: 'CATEGORY_VALIDATION_ERR',
    DELETE_CATEGORY_ERR: 'DELETE_CATEGORY_ERR',
    DELETE_FLASHCARD_ERR: 'DELETE_FLASHCARD_ERR',
    GET_CATEGORY_ERR: 'GET_CATEGORY_ERR',
    GET_FLASHCARD_ERR: 'GET_FLASHCARD_ERR',
    GET_FLASHCARDS_ERR: 'GET_FLASHCARDS_ERR',
    GET_USER_ERR: 'GET_USER_ERR',
    LOGIN_ERR: 'LOGIN_ERR',
    NEW_CATEGORY_ERR: 'NEW_CATEGORY_ERR',
    NEW_FLASHCARD_ERR: 'NEW_FLASHCARD_ERR',
    USER_VALIDATION_ERR: 'USER_VALIDATION_ERR'
};